travis:
  secure:
    BINSTAR_TOKEN: wVkE3Zygrcp1GEJggY5jej76vM+EFXrlihKFi/0my1wbkriu0ZLKi5dF38xDyar2913NwhK0/uNAtnXr+aQ/a0S8/eflBuXUTtfNPpLo9QYe8j+2aBYLhyfXZ2j+vZRXHxxOmhQ+vrLhEyTChT7WIG/4HbzjUB28e3vYy56xZv0VwcupIW5xLwSGmbQ/8kKnOkiqUB9Tv4qsOW0QYDtAFhcYfU0weEYWsBpS7ZYXcE8TOWZ2AklWQ5QlqknPvYdAN9QtBaLJl2X5OQ7bKLu6P1R3Zz2hUM4EN9EUyul/aATzm7HMHp2xQzXiklN73KtEQ0l7BDHTNwZ6I9qWxgnxHdLUGsZiTlhmVmNESlkG6aKdfQ0Vq4oqBHM+LN7IDW6tcpSQFBl8FAu+CCajOcbYUql7wgHSm1AiL2Hyt38P+3asNfL2n87houoAhyyutreB291x5wrDEUAQmUluRcjarSV2JvW+lHvibJQ3YKG8GzQH77+Oni5zZOG3/UGLFyDWRCHiYun9TJFMrJbmFbukLJtXr555ligiuyR3Sbdp2X4xY3nRDb5KkrBuv+6jqsTpD2vo6GXZZ4ZVB63j6syfQ6Y0E6S1yLN7mlrNM/pPrJAwINc6yJ9riOwAXgsN889b4LJLw5n5XzHsHsAB1Bno9ykuso8cuw7B2G+NwgNgS9g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
